---
title: "proj-apr2023"
output:
  pdf_document: default
  word_document: default
  html_document: default
date: "2023-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading the dataset
```{r}
path <- file.choose()
```

```{r}
df <- read.csv(path)
head(df)
```

Handling the NA Values with mean of the feature records
```{r}
df$radius_mean <- ifelse(is.na(df$radius_mean),
                     ave(df$radius_mean, FUN = function(x)mean(x, na.rm = TRUE)),
                     df$radius_mean)
df$area_mean <- ifelse(is.na(df$area_mean),
                     ave(df$area_mean, FUN = function(x)mean(x, na.rm = TRUE)),
                     df$area_mean)
df$concave.points_worst <- ifelse(is.na(df$concave.points_worst),
                     ave(df$concave.points_worst, FUN = function(x)mean(x, na.rm = TRUE)),
                     df$concave.points_worst)
df$area_worst = ifelse(is.na(df$area_worst),
                     ave(df$area_worst, FUN = function(x)mean(x, na.rm = TRUE)),
                     df$area_worst)
df$concave.points_mean = ifelse(is.na(df$concave.points_mean),
                     ave(df$concave.points_mean, FUN = function(x)mean(x, na.rm = TRUE)),
                     df$concave.points_mean)
df$area_se = ifelse(is.na(df$area_se),
                     ave(df$area_se, FUN = function(x)mean(x, na.rm = TRUE)),
                     df$area_se)
df$concavity_se = ifelse(is.na(df$concavity_se),
                     ave(df$concavity_se, FUN = function(x)mean(x, na.rm = TRUE)),
                     df$concavity_se)
```

Removing the ID Column as this doesn't affect the result
```{r}
df$id <- NULL
```

Encoding the Categorical data for Diagnosis
```{r}
df$diagnosis <- factor(df$diagnosis,levels = c('M','B'),labels = c(1, 2))
head(df)
```

Splitting the data into train and test data using dplyr
```{r}
library(dplyr)
df$id <- 1:nrow(df)

# Splitting into 80-training and 20-test dataset
trn <- df%>%dplyr::sample_frac(0.80)
tst <- dplyr::anti_join(df,trn,by='id')

trn$id <- NULL
tst$id <- NULL
df$id <- NULL
```
```{r}
head(trn)
```
```{r}
head(tst)
```

Implementing decision tree classifier
```{r}
library(caTools)
library(party)
dt <- ctree(diagnosis~., trn)
plot(dt)
```
```{r}
dt
```
```{r}
pred <- predict(dt,tst)
pred
```
```{r}
library(caret)
confusionMatrix(pred, tst$diagnosis)
```